export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    VENDOR_REGISTER: "/auth/vendor/register",
    GOOGLE: "/auth/google",
    ME: "/auth/me",
    USERS: "/auth/users",
    ADMIN_VENDORS: "/auth/admin/vendors",
    ADMIN_VENDOR_BY_ID: (id: string) => `/auth/admin/vendors/${id}`,
    ADMIN_VENDOR_STATUS: (id: string) => `/auth/admin/vendors/${id}/status`,
    VENDOR_STATS: "/auth/vendor/stats",
  },
  CATEGORIES: {
    BASE: "/categories",
    TREE: "/categories/tree",
    ADMIN_ALL: "/categories/admin/all",
    SLUG: (slug: string) => `/categories/slug/${encodeURIComponent(slug)}`,
    BY_ID: (id: string) => `/categories/${id}`,
    STATUS: (id: string) => `/categories/${id}/status`,
  },
  PRODUCTS: {
    BASE: "/products",
    FEATURED: "/products/featured",
    VISUAL_SEARCH: "/products/visual-search",
    SEARCH_FACETS: "/products/search/facets",
    SEARCH_SUGGESTIONS: "/products/search/suggestions",
    SEARCH_POPULAR: "/products/search/popular",
    SEARCH_TRACK: "/products/search/track",
    SEARCH_HISTORY: "/products/search/history",
    SEARCH_HISTORY_CLEAR: "/products/search/history/clear",
    SYNC_EMBEDDINGS: "/products/admin/sync-embeddings",
    ADMIN_ALL: "/products/admin/all",
    SLUG: (slug: string) => `/products/slug/${encodeURIComponent(slug)}`,
    BY_ID: (id: string) => `/products/${id}`,
    STATUS: (id: string) => `/products/${id}/status`,
    VARIANTS: (productId: string) => `/products/${productId}/variants`,
    VARIANT_BY_ID: (variantId: string) => `/products/variants/${variantId}`,
  },
  CART: {
    BASE: "/cart",
    ITEMS: "/cart/items",
    ITEM_BY_ID: (id: string) => `/cart/items/${id}`,
    CLEAR: "/cart/clear",
    SYNC: "/cart/sync",
  },
  ORDERS: {
    CHECKOUT: "/orders/checkout",
    VERIFY_PAYMENT: "/orders/verify-payment",
    PAYMENT_FAILED: "/orders/payment-failed",
    RETRY_PAYMENT: (id: string) => `/orders/my-orders/${id}/retry-payment`,
    ADDRESSES: "/orders/addresses",
    MY_ORDERS: "/orders/my-orders",
    MY_RETURNS: "/orders/my-returns",
    MY_ORDER_BY_ID: (id: string) => `/orders/my-orders/${id}`,
    MY_ORDER_PDF: (id: string) => `/orders/my-orders/${id}/pdf`,
    MY_ORDER_INVOICE: (id: string) => `/orders/my-orders/${id}/invoice`,
    CANCEL_MY_ORDER: (id: string) => `/orders/my-orders/${id}/cancel`,
    REQUEST_RETURN: (id: string) => `/orders/my-orders/${id}/return`,
    MY_ORDER_RETURN: (id: string) => `/orders/my-orders/${id}/return`,
    ADMIN_STATS: "/orders/admin/stats",
    ADMIN_ALL: "/orders/admin/all",
    ADMIN_BY_ID: (id: string) => `/orders/admin/${id}`,
    ADMIN_ORDER_PDF: (id: string) => `/orders/admin/${id}/pdf`,
    ADMIN_ORDER_INVOICE: (id: string) => `/orders/admin/${id}/invoice`,
    ADMIN_STATUS: (id: string) => `/orders/admin/${id}/status`,
    ADMIN_RETURNS: "/orders/admin/returns",
    ADMIN_RETURN_BY_ID: (id: string) => `/orders/admin/returns/${id}`,
    ADMIN_RETURN_STATUS: (id: string) => `/orders/admin/returns/${id}/status`,
  },
  PAYMENTS: {
    VERIFY: "/payments/verify",
    FAILED: "/payments/failed",
    RETRY: (id: string) => `/payments/retry/${id}`,
  },
  UPLOAD: {
    SINGLE: "/upload/single",
    MULTIPLE: "/upload/multiple",
  },
  BANNERS: {
    ACTIVE: "/banners/active",
    ADMIN_ALL: "/banners/admin/all",
    BY_ID: (id: string) => `/banners/${id}`,
    STATUS: (id: string) => `/banners/${id}/status`,
  },
  REVIEWS: {
    BY_PRODUCT: (productId: string) => `/reviews/product/${productId}`,
    MY_REVIEW: (productId: string) => `/reviews/product/${productId}/my-review`,
    BY_ID: (id: string) => `/reviews/${id}`,
    ADMIN_ALL: "/reviews/admin/all",
    ADMIN_STATS: "/reviews/admin/stats",
    ADMIN_STATUS: (id: string) => `/reviews/admin/${id}/status`,
    ADMIN_BY_ID: (id: string) => `/reviews/admin/${id}`,
    ADMIN_TOP_PRODUCTS: "/reviews/admin/top-products",
    TOP_PRODUCTS: "/reviews/top-products",
  },
  WISHLIST: {
    BASE: "/wishlist",
    ITEMS: "/wishlist/items",
    ITEM_BY_PRODUCT_ID: (productId: string) => `/wishlist/items/${productId}`,
    TOGGLE: "/wishlist/toggle",
    CLEAR: "/wishlist/clear",
  },
  VISITS: {
    TRACK: (productId: string) => `/products/${productId}/visit`,
    STATUS: (productId: string) => `/products/${productId}/visit-status`,
    HIGHLY_INTERESTED: "/products/user/highly-interested",
    RECENT: "/visits/recent",
    ADMIN_ALL: "/visits/admin/all",
    ADMIN_RANKED: "/visits/admin/ranked-products",
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    MARK_ALL_READ: "/notifications/mark-all-read",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    BY_ID: (id: string) => `/notifications/${id}`,
  },
} as const;


