export const APP_CONFIG = {
  APP_NAME: "E-Commerce",
  APP_TAGLINE: "Next-Gen Luxury E-Commerce Catalog",
  CURRENCY_SYMBOL: "₹",
  CURRENCY_CODE: "INR",
  DEFAULT_PAGE_SIZE: 12,
  DEFAULT_ADMIN_PAGE_SIZE: 10,
  FREE_SHIPPING_THRESHOLD: 499,
  STANDARD_SHIPPING_FEE: 49,
  TOAST_DURATION_MS: 5000,
  MAX_UPLOAD_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
  MAX_UPLOAD_FILES: 10,
} as const;
